SELECT o.LOCATION AS LOCATION
    , TO_TIMESTAMP_NTZ(o.ORDER_DATE) AS TIMESTAMP
    , SUM(o.AMOUNT) AS SALES_AMOUNT
FROM SALES.ORDERS o
WHERE o.ORDER_DATE < CURRENT_DATE()
GROUP BY
    o.LOCATION
    , o.ORDER_DATE
