SELECT o.LOCATION
    , TO_TIMESTAMP_NTZ(o.ORDER_DATE) AS TIMESTAMP
    , EXTRACT(DAYOFWEEK FROM o.ORDER_DATE) AS day_of_week
    , EXTRACT(MONTH FROM o.ORDER_DATE) AS month    
    , h.HOLIDAY_LIST
    , SUM(o.AMOUNT) AS SALES_AMOUNT
FROM SALES.ORDERS o
LEFT JOIN (
            SELECT DATE
                ,LISTAGG(HOLIDAY_NAME, ', ') WITHIN GROUP (ORDER BY HOLIDAY_NAME) AS HOLIDAY_LIST
            FROM MASTER.HOLIDAYS
            GROUP BY DATE
) h
    ON h.DATE = o.ORDER_DATE
GROUP BY
    o.LOCATION
    , o.ORDER_DATE
    , h.HOLIDAY_LIST