DECLARE 
v_rows_loaded INTEGER DEFAULT 0; 
v_load_id STRING DEFAULT UUID_STRING();
BEGIN 

-- 2) Copy into staging with PATTERN argument 
EXECUTE IMMEDIATE 
'COPY INTO ' || DB_NAME || '.' || SCHEMA_NAME || '.STG_' || TARGET_TABLE || '
  FROM @' || DB_NAME || '.' || SCHEMA_NAME || '.' || STAGE_NAME || '
  FILE_FORMAT = (FORMAT_NAME = ' || DB_NAME || '.' || SCHEMA_NAME || '.' || FILE_FORMAT_NAME || ')
  PATTERN = ''' || PATTERN || '''
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  INCLUDE_METADATA = (SRC_FILENAME = METADATA$FILENAME, SRC_ROW_NUMBER = METADATA$FILE_ROW_NUMBER)
  ON_ERROR = ''ABORT_STATEMENT''
';
  -- tag all staged rows with the same batch id (safe because TRUNCATE after merge)
  EXECUTE IMMEDIATE 'UPDATE '||DB_NAME||'.'||SCHEMA_NAME||'.STG_'||TARGET_TABLE||' SET LOAD_ID = ?'
  USING (v_load_id);

  -- 3) Merge into target 
EXECUTE IMMEDIATE 

  'MERGE INTO ' || TARGET_TABLE || ' AS T 
  USING STG_' || TARGET_TABLE || ' AS S 
    ON T.ORDER_ID = S.ORDER_ID AND T.ITEM_ID = S.ITEM_ID
  WHEN MATCHED THEN UPDATE SET 
    T.AMOUNT          = S.AMOUNT,
    T.SRC_FILENAME    = S.SRC_FILENAME,
    T.SRC_ROW_NUMBER  = S.SRC_ROW_NUMBER,
    T.UPDATED_AT      = CURRENT_TIMESTAMP(),
    T.UPDATED_BY      = '''|| SPROC_NAME ||''',
    T.LOAD_ID         = S.LOAD_ID
  WHEN NOT MATCHED THEN INSERT 
    ( ORDER_ID, ITEM_ID, AMOUNT, SRC_FILENAME, SRC_ROW_NUMBER, CREATED_AT, CREATED_BY, LOAD_ID ) 
  VALUES ( S.ORDER_ID, S.ITEM_ID, S.AMOUNT, S.SRC_FILENAME, S.SRC_ROW_NUMBER, CURRENT_TIMESTAMP(), '''|| SPROC_NAME ||''', S.LOAD_ID );
'; 

EXECUTE IMMEDIATE
    'TRUNCATE TABLE STG_' || TARGET_TABLE || ';';
  
RETURN 'Loaded rows into ' || TARGET_TABLE || ';';

END;