SELECT ORDER_DATE
    , ORDER_ID
    , AMOUNT
FROM SALES.ORDERS o
WHERE EXISTS(
    SELECT 1
    FROM SECURITY.ENTITY_GROUP_MEMBERSHIPS gm
    INNER JOIN SECURITY.ENTITY_GROUP_LOCATIONS gs
        ON gs.GROUP_NAME = gm.GROUP_NAME
    WHERE gs.STORE_ID = o.LOCATION
    AND(
        (gm.PRINCIPAL_TYPE = 'ROLE' AND IS_ROLE_IN_SESSION(gm.principal_name))

        OR(gm.PRINCIPAL_TYPE = 'USER' AND gm.principal_name = CURRENT_USER())
    )
)
;

